// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDA59-2ts3eylSRHcgPEApw85eSaYXHGbQ',
    appId: '1:857942637040:web:dddef64e90085e8e118535',
    messagingSenderId: '857942637040',
    projectId: 'women-safety-eb95b',
    authDomain: 'women-safety-eb95b.firebaseapp.com',
    storageBucket: 'women-safety-eb95b.appspot.com',
    measurementId: 'G-CK715PQCQY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgcikgErESOKd-pKQ9BxiOOovQNDEBarM',
    appId: '1:857942637040:android:78d160a0ce2ba727118535',
    messagingSenderId: '857942637040',
    projectId: 'women-safety-eb95b',
    storageBucket: 'women-safety-eb95b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBlbs1mp-RKCHWecFNdnUmMtACIswhi2zw',
    appId: '1:857942637040:ios:9ff03fdfd1702fed118535',
    messagingSenderId: '857942637040',
    projectId: 'women-safety-eb95b',
    storageBucket: 'women-safety-eb95b.appspot.com',
    iosBundleId: 'com.example.learnFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBlbs1mp-RKCHWecFNdnUmMtACIswhi2zw',
    appId: '1:857942637040:ios:9ff03fdfd1702fed118535',
    messagingSenderId: '857942637040',
    projectId: 'women-safety-eb95b',
    storageBucket: 'women-safety-eb95b.appspot.com',
    iosBundleId: 'com.example.learnFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDA59-2ts3eylSRHcgPEApw85eSaYXHGbQ',
    appId: '1:857942637040:web:bd2ca11720c2e7ff118535',
    messagingSenderId: '857942637040',
    projectId: 'women-safety-eb95b',
    authDomain: 'women-safety-eb95b.firebaseapp.com',
    storageBucket: 'women-safety-eb95b.appspot.com',
    measurementId: 'G-26JXCWW520',
  );
}
